# Generated by Django 5.0.14 on 2025-04-26 11:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Área Responsable',
                'verbose_name_plural': 'Áreas Responsables',
                'db_table': 'ac_areas_responsables',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_labor', models.CharField(blank=True, max_length=255, verbose_name='Sub Labor')),
                ('productividad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Productividad')),
                ('programa', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Programa')),
                ('real', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Real')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('area_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agrochapi.arearesponsable', verbose_name='Área Responsable')),
                ('consumidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.consumidor', verbose_name='Consumidor')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programa_mo_creados', to=settings.AUTH_USER_MODEL)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cultivo', verbose_name='Cultivo')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.calendar', verbose_name='Fecha')),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fundo', verbose_name='Fundo')),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.labor', verbose_name='Labor')),
                ('record_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.recordstatus')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.umedida', verbose_name='Unidad de Medida')),
            ],
            options={
                'verbose_name': 'Programa MO',
                'verbose_name_plural': 'Programas MO',
                'db_table': 'ac_programa_mo',
                'unique_together': {('fecha', 'fundo', 'cultivo', 'labor', 'consumidor', 'unidad_medida', 'area_responsable')},
            },
        ),
    ]
