# Generated by Django 5.0.14 on 2025-05-07 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agrochapi', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='programamo',
            name='consumidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.consumidor', verbose_name='Consumidor'),
        ),
        migrations.AddField(
            model_name='programamo',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programa_mo_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programamo',
            name='fecha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.calendar', verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='programamo',
            name='labor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.labor', verbose_name='Labor'),
        ),
        migrations.AddField(
            model_name='programamo',
            name='record_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.recordstatus'),
        ),
        migrations.AddField(
            model_name='programamo',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.umedida', verbose_name='Unidad de Medida'),
        ),
        migrations.AlterUniqueTogether(
            name='programamo',
            unique_together={('fecha', 'labor', 'consumidor', 'unidad_medida', 'area_responsable')},
        ),
    ]
