# Generated by Django 5.0.14 on 2025-05-07 09:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'tb_actividad',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('month_number', models.PositiveSmallIntegerField()),
                ('month_name', models.CharField(max_length=20)),
                ('iso_week', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Fecha del Calendario',
                'verbose_name_plural': 'Fechas del Calendario',
                'db_table': 'tb_calendar',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cultivo',
                'verbose_name_plural': 'Cultivos',
                'db_table': 'tb_cultivos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Fundo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Fundo',
                'verbose_name_plural': 'Fundos',
                'db_table': 'tb_fundos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'tb_modules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecordStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('level', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Estado de Registro',
                'verbose_name_plural': 'Estados de Registro',
                'db_table': 'tb_record_status',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hierarchy', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'tb_roles',
                'ordering': ['-hierarchy'],
            },
        ),
        migrations.CreateModel(
            name='UMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('u_medida', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'tb_unidades_medida',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/photos/')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_users', to='auth.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.role')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'tb_custom_users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actividad')),
            ],
            options={
                'verbose_name': 'Labor',
                'verbose_name_plural': 'Labores',
                'db_table': 'tb_labor',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='LoginRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Record',
                'verbose_name_plural': 'Login Records',
                'db_table': 'tb_login_records',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cultivo')),
            ],
            options={
                'verbose_name': 'Variedad',
                'verbose_name_plural': 'Variedades',
                'db_table': 'tb_variedades',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Consumidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre_corto', models.CharField(blank=True, max_length=5, null=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField()),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('directo', 'Directo'), ('indirecto', 'Indirecto')], default='directo', max_length=10)),
                ('grupo_manejo', models.CharField(blank=True, max_length=100, null=True)),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fundo')),
                ('variedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.variedad')),
            ],
            options={
                'verbose_name': 'Consumidor',
                'verbose_name_plural': 'Consumidores',
                'db_table': 'tb_consumidores',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ConsumerCampaignCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivo', models.CharField(max_length=50)),
                ('campaign_label', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('postcosecha_start', models.DateField(blank=True, null=True)),
                ('poda_start', models.DateField(blank=True, null=True)),
                ('cosecha_end', models.DateField(blank=True, null=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consumidor')),
            ],
            options={
                'verbose_name': 'Calendario de Campañas por Consumidor',
                'db_table': 'tb_campaign_calendar',
                'ordering': ['consumer', 'campaign_label'],
                'unique_together': {('consumer', 'campaign_label')},
            },
        ),
        migrations.CreateModel(
            name='RoleModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.module')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role')),
            ],
            options={
                'verbose_name': 'Role Module Permission',
                'verbose_name_plural': 'Role Module Permissions',
                'db_table': 'tb_role_module_permissions',
                'ordering': ['role', 'module'],
                'unique_together': {('role', 'module')},
            },
        ),
    ]
